version: '3'

vars:
  BIN_DIR: bin

tasks:
  setup:
    desc: Install all dependencies (Backend, CLI, Frontend)
    cmds:
      - echo "==> Installing backend dependencies..."
      - cd backend && go mod download
      - echo "==> Installing CLI dependencies..."
      - cd cli && go mod download
      - echo "==> Installing frontend dependencies..."
      - cd frontend && npm install
      - echo "==> Done. Run 'task dev' to start the development stack."

  dev:
    desc: Start backend and frontend dev servers concurrently
    deps: [dev-backend, dev-frontend]

  dev-backend:
    desc: Start backend dev server
    dir: backend
    cmds:
      - go run ./cmd/server/

  dev-frontend:
    desc: Start frontend dev server
    dir: frontend
    cmds:
      - npm run dev

  build:
    desc: Build all components (Backend, CLI, Frontend)
    cmds:
      - task: build-backend
      - task: build-cli
      - task: build-frontend

  build-backend:
    desc: Build backend binary
    dir: backend
    cmds:
      - mkdir -p ../{{.BIN_DIR}}
      - go build -o ../{{.BIN_DIR}}/server.exe ./cmd/server/

  build-cli:
    desc: Build CLI binary
    dir: cli
    cmds:
      - mkdir -p ../{{.BIN_DIR}}
      - go build -o ../{{.BIN_DIR}}/kanbin.exe ./cmd/kanbin/

  build-frontend:
    desc: Build frontend production bundle
    dir: frontend
    cmds:
      - npm run build

  test:
    desc: Run all tests
    cmds:
      - task: test-backend
      - task: test-cli
      - task: test-frontend

  test-backend:
    desc: Run backend tests
    dir: backend
    cmds:
      - go test ./...

  test-cli:
    desc: Run CLI tests
    dir: cli
    cmds:
      - go test ./...

  test-frontend:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - npm run test

  lint:
    desc: Lint all components
    cmds:
      - task: lint-backend
      - task: lint-cli
      - task: lint-frontend

  lint-backend:
    desc: Lint backend
    dir: backend
    cmds:
      - golangci-lint run ./...

  lint-cli:
    desc: Lint CLI
    dir: cli
    cmds:
      - golangci-lint run ./...

  lint-frontend:
    desc: Lint frontend
    dir: frontend
    cmds:
      - npm run lint

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}/
      - rm -rf frontend/dist/
      - echo "==> Done."
