# Build stage
FROM golang:1.24-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o server ./cmd/server

# Production stage
FROM alpine:latest

WORKDIR /app
COPY --from=build /app/server .
COPY --from=build /app/migrations ./migrations

EXPOSE 8080

CMD ["./server"]
